# Generated by Django 3.1.7 on 2021-03-09 16:46

from django.db import migrations, models
import django.db.models.deletion
import sloth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('last', models.FileField(upload_to='last_report')),
                ('last_year', models.FileField(upload_to='last_y_report')),
                ('tag', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=16)),
                ('year', models.PositiveSmallIntegerField()),
                ('open_last_report', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to=sloth.models.user_directory_path)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sloth.report')),
            ],
        ),
    ]
