# Generated by Django 3.1.7 on 2021-03-09 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sloth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='file',
            field=models.FileField(upload_to='user_directory_path'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='variable',
            name='month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='images.jpg', upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
