# Generated by Django 3.1.7 on 2021-03-09 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sloth', '0004_auto_20210309_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='variable',
            name='year',
            field=models.PositiveSmallIntegerField(default=2021),
        ),
    ]
